### ISSUE TITLE
JS error if something invalid saved FB Page ID field

### ISSUE THREAD

**Issue by craigschlegel** [smashballoon/custom-facebook-feed#23]
https://smashballoon.freshdesk.com/a/tickets/271814

**Comment by johnnybrackett** [comment]
Definitely an oversight on my part when adding the account management stuff that someone would manually connect an account and add the full Facebook page URL rather than just the page ID.  People do this sometimes when adding their ID to the Facebook Page ID field, but on the front end I just parse the URL and grab the ID from it using the code below.  We can just do the same here so that only the ID is saved when connecting an account rather than the full URL:

```
//If user pastes their full URL into the Page ID field then strip it out
$cff_facebook_string = 'facebook.com';
( stripos($page_id, $cff_facebook_string) !== false) ? $cff_page_id_url_check = true : $cff_page_id_url_check = false;

if ( $cff_page_id_url_check === true ) {
    //Remove trailing slash if exists
    $page_id = preg_replace('{/$}', '', $page_id);
    //Get last part of url
    $page_id = substr( $page_id, strrpos( $page_id, '/' )+1 );
}

//If the Page ID contains a query string at the end then remove it
if ( stripos( $page_id, '?') !== false ) $page_id = substr($page_id, 0, strrpos($page_id, '?'));
```
